version: '3.4'

name: exam_node

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.2
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_pass
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
  adminer:
    image: adminer:latest
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN=dracula
    ports:
        - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  db-data:
    driver: local
